#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := AWS_IoT_Anlytics-for-Thermometer
PROJECT_VER := 1.0.0

include $(IDF_PATH)/make/project.mk

